apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpetstore-dplymt
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: jpet
  template:
    metadata:
      labels:
        bb: jpet
    spec:
      containers:
      - name: jpet-store
        image: 693161137177.dkr.ecr.us-east-1.amazonaws.com/jpetartifactrepo:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jpetstore-svc
  namespace: default
spec:
  type: NodePort
  selector:
    bb: jpet
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
